services:
  nginx:
    container_name: gs-nginx
    image: nginx:1-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"
